M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu20.04.1} date Tue 28 Jun 2022 09:19:20 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-28T21:19:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.250
%
G90
G05
T1
X124.206Y-118.354
X135.636Y-118.354
T0
M30
