M48
; DRILL file {KiCad 6.0.6-3a73a75311~116~ubuntu20.04.1} date Wed 20 Jul 2022 09:27:02 AM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-20T09:27:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.6-3a73a75311~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.250
%
G90
G05
T1
X124.24Y-118.34
X135.67Y-118.34
T0
M30
